FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/registrations-manager-api.jar registration-service.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "registration-service.jar"]

# Environment variables
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres