FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/organization-manager-api.jar organization-service.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "organization-service.jar"]

# Environment variables
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres