FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/configuration-service.jar configuration-service.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "configuration-service.jar"]

# Environment variables
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres